### ISSUE TITLE
Too many "MARK COMPLETE" buttons

### ISSUE THREAD

**Issue by jessetipton** [orcudy/MakeSchoolNotesTutorial#10]
I don't know the nuances of how these tutorials are built, but there appears to be a superfluous amount of "MARK COMPLETE" buttons throughout. An example:

<img width="739" alt="screen shot 2016-06-10 at 2 02 42 pm" src="https://cloud.githubusercontent.com/assets/2132778/15978613/0dae9092-2f14-11e6-8898-eb9610de4b38.png">

**Comment by danielhaaser** [comment]
Fixed in a4ea488d98da5a0d6bca94f715bf61151e8964b3
