### ISSUE TITLE
calling reloadData() from another viewController

### ISSUE THREAD

**Issue by Frostao** [orcudy/MakeSchoolNotesTutorial#12]
It is not really best practice to call reloadData() from another viewController.

**Comment by danielhaaser** [comment]
I agree, I think this will be fixed as part of #5.

**Comment by danielhaaser** [comment]
I removed one of the offending `reloadData()` calls, but I'm going to have to leave one offensive `reloadData()` call in the project. It's eventually overwritten by other code and won't end up in the student's final project.

I'm not super happy about it, but it doesn't feel like the right time to delve into more abstract concepts like encapsulation in this tutorial. I think it might be confusing in context. Encapsulation will be covered in Makestagram.

**Comment by danielhaaser** [comment]
Half-fixed in 3243e57ece6d7a3a553bcddd203bb2116a4f2f5f
