### ISSUE TITLE
7. Intro to Bar Button Items – Can't Mark Completion

### ISSUE THREAD

**Issue by ocwang** [orcudy/MakeSchoolNotesTutorial#14]
Marking completion for the two sections, "Introducing Unwind Segues" and "Adding Unwind Segue Identifiers," don't persist. After refreshing the page or moving forward to the next section, the two sections revert to being incomplete. I haven't had a problem with any of the other sections in the tutorial.

**Comment by dionlarson** [comment]
Just tested and works for me now. Let me know if you see it happening again and I'll try opening a ticket for web team.
