### ISSUE TITLE
Naming a view controller

### ISSUE THREAD

**Issue by cliffweitzman** [orcudy/MakeSchoolNotesTutorial#15]
In section 5. Creating View Controllers

![image](https://cloud.githubusercontent.com/assets/3460171/15987628/5fe3cde4-2fe3-11e6-8269-ba3da1184e13.png)
The picture provided is not comprehensive enough for a first time student. 
It should be made more clear that in order to name a view controller a student must highlight the view controller then show the identity inspector on the right panel, then type the name of the view controller code file into the class section of the identity inspector. Like so:

![image](https://cloud.githubusercontent.com/assets/3460171/15987622/079f0716-2fe3-11e6-91c1-305cdd41f280.png)

**Comment by danielhaaser** [comment]
Fixed in 8f8f0e27fe7a6b6923d9dce1bd619d07b8dce38b
