### ISSUE TITLE
Typo above "Show solution" at Update Notes section

### ISSUE THREAD

**Issue by wustladela** [orcudy/MakeSchoolNotesTutorial#19]
https://www.makeschool.com/academy/tutorial/learn-how-to-build-make-school-notes-635ec931-1be2-4965-9122-c3a35ac41e26/creating-realm-helper-methods

If you couldn't figure it out on your own, that's okay. It's a little hard to **explan**, but reading the code should make it pretty clear what's happening:

**Comment by danielhaaser** [comment]
Fixed in b284a8b8c9141697d8d4823d5fc13751d883c7b1
