### ISSUE TITLE
Needed link changes

### ISSUE THREAD

**Issue by orcudy** [orcudy/MakeSchoolNotesTutorial#2]
- **P00** 
  1. Make School Notes Starter Project\* should point to starter project in Make School Notes repo. (Currently pointing to orcudy repo.)
- **P01** 
  1. has a link that should point to: `Additional Content > tableViews > content.md`.
- **P02** 
  1. has a link that should point to the Introduction to Interface Builder tutorial.

**Comment by dionlarson** [comment]
Fixed in aa7ae20
