### ISSUE TITLE
Error Tutorial

### ISSUE THREAD

**Issue by cliffweitzman** [orcudy/MakeSchoolNotesTutorial#21]
![image](https://cloud.githubusercontent.com/assets/3460171/15994547/94dfd1f8-30bc-11e6-952e-e28245289520.png)

The error tutorial mentioned here si not live/ broken link

**Comment by danielhaaser** [comment]
Fixed in 13fc4e4e85f2f5abbd43b7f1a3f8b4f37172a2ec
