### ISSUE TITLE
2. (Displaying Information with our Table View section) - a bit more explanation on dequeueReusableCellWithIdentifier

### ISSUE THREAD

**Issue by MichaelMeinberg** [orcudy/MakeSchoolNotesTutorial#25]
This part is great: 

_Notice that we are dequeueing a reusable cell. This is actually an interesting performance optimization: it turns out that it's fairly expensive to create and lay out a brand new UITableViewCell. So instead of creating new cells as they're about to display on screen, and destroying them as they scroll out of view, UITableView relies on giving us previously constructed cells for us to update with new information. If there's no recycled cells ready to be reused, dequeueReusableCellWithIdentifier(_:forIndexPath:) will give us a new one instead._

But how about adding something like:  "The nice thing is that this is all handled for you automatically by the compiler, Apple figures out what it can reuse and what needs to be created in the background!  All you have to do is call dequeueReusableCellWithIdentifier".

**Comment by danielhaaser** [comment]
Fixed in fc1149c70864ce4eeaa26026fb4fe3582ec21e8e
