### ISSUE TITLE
P08 order of instructions

### ISSUE THREAD

**Issue by Frostao** [orcudy/MakeSchoolNotesTutorial#28]
I feel like when the following instruction was presented in a wrong order.

``` swift
if viewController is PhotoViewController {
        takePhoto()
        return false
    } else {
        return true
}
```

The function takePhoto() should be presented before or together with this code. It makes some people(like me) ask questions to their instructors right away. Also the property declaration should be presented before.

**Comment by danielhaaser** [comment]
Wrong repository!

**Comment by danielhaaser** [comment]
Please move the issue
