### ISSUE TITLE
Needs to Show the Final Product Early

### ISSUE THREAD

**Issue by danielhaaser** [orcudy/MakeSchoolNotesTutorial#29]
To give the students a better idea and some context, app should be demonstrated in the first page

**Comment by dionlarson** [comment]
<img width="576" alt="screenshot 2016-06-19 12 59 56" src="https://cloud.githubusercontent.com/assets/1843883/16179541/c0d7771e-361d-11e6-8495-7a98b7fa79f0.png">

This is already on the first page as a video?
