### ISSUE TITLE
Update notes property with property observer in all of tutorial

### ISSUE THREAD

**Issue by orcudy** [orcudy/MakeSchoolNotesTutorial#5]
Currently, a property observer is being used to reload table view data in the persistence modules, but not in any of the other modules.

Property observers is the way to go, so update the earlier modules.

**Comment by dionlarson** [comment]
Should be part of a challenges section.

**Comment by danielhaaser** [comment]
This won't really work as a challenge, because the final project uses property observers. The intermediate stages can be updated to use them, however.

**Comment by danielhaaser** [comment]
Fixed in 3243e57ece6d7a3a553bcddd203bb2116a4f2f5f
