### ISSUE TITLE
Needs challenges section

### ISSUE THREAD

**Issue by dionlarson** [orcudy/MakeSchoolNotesTutorial#7]
Would be nice to have a challenges section for extending the features.

See #5 and have them try restyling the app as they did at the end of the Tip Calculator.

**Comment by danielhaaser** [comment]
Making the app look prettier is nice

**Comment by cliffweitzman** [comment]
At the moment notes are stacked with the newest note at the bottom. That is not ideal. A great challenge would be to have the students make changes to the code so that notes stack with the newest note on top and the last note on bottom.

**Comment by cliffweitzman** [comment]
Another great challenge would be to add a truncated version of the note body into the table view cell as is present in the native apple notes app. This would require students to go back and enlarge the size of the prototype cell, add and connect a label, and populate it from note.content. Though, this may be a bit challenging at this point.
