### ISSUE TITLE
P05 Initial view controller

### ISSUE THREAD

**Issue by Frostao** [orcudy/MakeSchoolNotesTutorial#8]
In the end of this tutorial, you forgot to mention to change the initial view controller back to the original one.

**Comment by danielhaaser** [comment]
Correct me if I'm wrong, but I think this is a non-issue... we intend for the student to have set the navigation controller as the initial view controller at the end of P05

**Comment by nikolasburk** [comment]
I think a note reminding them to do so before going to the next page would be helpful.

**Comment by nikolasburk** [comment]
Just saw that there is a reminder on page 6., so never mind...
